import { Profile, Article, CaseStudy, Career, Service, Consultation, Testimonial, PricingPlan } from './types';

export const isDemoMode = () => {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  return !supabaseUrl || supabaseUrl === '' || supabaseUrl.includes('placeholder');
};

export const demoUser = {
  id: 'demo-user-id',
  email: 'admin@biglabs.io',
  created_at: new Date().toISOString(),
};

export const demoProfile: Profile = {
  id: 'demo-user-id',
  created_at: new Date().toISOString(),
  email: 'admin@biglabs.io',
  first_name: 'Alexandra',
  last_name: 'Chen',
  avatar_url: null,
  company_name: 'Biglabs Consulting',
  role: 'Managing Partner',
  phone: '+1 (555) 000-0000',
};

export const demoServices: Service[] = [
  {
    id: '1',
    created_at: '2025-01-15T00:00:00Z',
    user_id: 'demo-user-id',
    title: 'Strategic Advisory',
    slug: 'strategic-advisory',
    description: 'C-suite strategy alignment, market positioning, and competitive analysis for enterprises navigating complex markets.',
    long_description: 'Our Strategic Advisory practice helps executive teams define and execute transformative strategies. We combine deep industry expertise with rigorous analytical frameworks to deliver actionable roadmaps.',
    icon: 'Target',
    features: ['Market Analysis', 'Competitive Intelligence', 'Growth Strategy', 'M&A Advisory', 'Board Advisory'],
    published: true,
    sort_order: 1,
  },
  {
    id: '2',
    created_at: '2025-01-15T00:00:00Z',
    user_id: 'demo-user-id',
    title: 'Digital Transformation',
    slug: 'digital-transformation',
    description: 'End-to-end modernization of legacy systems, cloud migration, and digital process optimization.',
    long_description: null,
    icon: 'Cpu',
    features: ['Legacy Modernization', 'Cloud Migration', 'Process Automation', 'Digital Roadmapping', 'Change Management'],
    published: true,
    sort_order: 2,
  },
  {
    id: '3',
    created_at: '2025-01-15T00:00:00Z',
    user_id: 'demo-user-id',
    title: 'AI & Machine Learning',
    slug: 'ai-machine-learning',
    description: 'Custom AI solutions, ML pipeline development, and intelligent automation for data-driven organizations.',
    long_description: null,
    icon: 'Brain',
    features: ['Custom AI Models', 'ML Pipeline Development', 'NLP Solutions', 'Computer Vision', 'AI Strategy'],
    published: true,
    sort_order: 3,
  },
  {
    id: '4',
    created_at: '2025-01-15T00:00:00Z',
    user_id: 'demo-user-id',
    title: 'Data & Analytics',
    slug: 'data-analytics',
    description: 'Business intelligence, predictive analytics, and data infrastructure for enterprise decision-making.',
    long_description: null,
    icon: 'BarChart3',
    features: ['Business Intelligence', 'Predictive Analytics', 'Data Warehousing', 'Real-time Dashboards', 'Data Governance'],
    published: true,
    sort_order: 4,
  },
  {
    id: '5',
    created_at: '2025-01-15T00:00:00Z',
    user_id: 'demo-user-id',
    title: 'Cybersecurity',
    slug: 'cybersecurity',
    description: 'Comprehensive security audits, compliance frameworks, and threat intelligence for modern enterprises.',
    long_description: null,
    icon: 'Shield',
    features: ['Security Audits', 'Compliance (SOC2, GDPR)', 'Threat Assessment', 'Incident Response', 'Zero Trust Architecture'],
    published: true,
    sort_order: 5,
  },
  {
    id: '6',
    created_at: '2025-01-15T00:00:00Z',
    user_id: 'demo-user-id',
    title: 'Operations Excellence',
    slug: 'operations-excellence',
    description: 'Process optimization, supply chain redesign, and operational efficiency for scalable growth.',
    long_description: null,
    icon: 'Settings',
    features: ['Process Optimization', 'Supply Chain Redesign', 'Lean Operations', 'Quality Management', 'Cost Reduction'],
    published: true,
    sort_order: 6,
  },
];

export const demoCaseStudies: CaseStudy[] = [
  {
    id: '1',
    created_at: '2025-06-01T00:00:00Z',
    user_id: 'demo-user-id',
    title: 'Global Banking Platform Modernization',
    slug: 'global-banking-modernization',
    client_name: 'Meridian Financial Group',
    industry: 'Financial Services',
    challenge: 'Legacy infrastructure causing 99.2% uptime with frequent outages during peak trading hours, resulting in $2.3M annual losses.',
    solution: 'Designed and executed a phased cloud migration strategy, moving 47 critical systems to a microservices architecture over 18 months while maintaining zero downtime.',
    results: 'Achieved 99.99% uptime, reduced infrastructure costs by 40%, and decreased deployment cycles from quarterly to daily.',
    metrics: [
      { label: 'Cost Reduction', value: '40%', description: 'Infrastructure spend decrease' },
      { label: 'Uptime', value: '99.99%', description: 'From 99.2% baseline' },
      { label: 'Deploy Speed', value: '90x', description: 'From quarterly to daily' },
      { label: 'Revenue Impact', value: '+$8.2M', description: 'Annual revenue recovery' },
    ],
    testimonial_quote: 'Biglabs didn\'t just modernize our systems—they transformed how we think about technology as a competitive advantage.',
    testimonial_author: 'Jonathan Park',
    testimonial_role: 'CTO, Meridian Financial Group',
    image_url: null,
    published: true,
  },
  {
    id: '2',
    created_at: '2025-08-15T00:00:00Z',
    user_id: 'demo-user-id',
    title: 'AI-Powered Diagnostic Pipeline',
    slug: 'ai-diagnostic-pipeline',
    client_name: 'Helix Health Systems',
    industry: 'Healthcare',
    challenge: 'Manual diagnostic processes averaging 72 hours per case, creating bottlenecks in patient care and increasing operational costs.',
    solution: 'Built a custom ML pipeline for automated preliminary diagnostics, integrating with existing EMR systems and training on 2M+ anonymized patient records.',
    results: 'Reduced diagnostic time by 85%, improved accuracy to 97.3%, and enabled the processing of 3x more cases per day.',
    metrics: [
      { label: 'Time Reduction', value: '85%', description: 'Diagnostic processing time' },
      { label: 'Accuracy', value: '97.3%', description: 'Diagnostic accuracy rate' },
      { label: 'Throughput', value: '3x', description: 'Cases processed per day' },
      { label: 'Cost Savings', value: '$4.1M', description: 'Annual operational savings' },
    ],
    testimonial_quote: 'The AI pipeline has fundamentally changed patient outcomes. What used to take three days now takes hours.',
    testimonial_author: 'Dr. Sarah Kimura',
    testimonial_role: 'Chief Medical Officer, Helix Health Systems',
    image_url: null,
    published: true,
  },
  {
    id: '3',
    created_at: '2025-10-01T00:00:00Z',
    user_id: 'demo-user-id',
    title: 'Supply Chain Intelligence Platform',
    slug: 'supply-chain-intelligence',
    client_name: 'Atlas Retail Corporation',
    industry: 'Retail & E-Commerce',
    challenge: 'Fragmented supply chain visibility across 200+ suppliers, leading to frequent stockouts and $15M in annual excess inventory.',
    solution: 'Implemented a real-time supply chain analytics platform with predictive demand forecasting, automated reordering, and supplier performance scoring.',
    results: 'Reduced stockouts by 67%, decreased excess inventory by 45%, and improved supplier on-time delivery from 78% to 96%.',
    metrics: [
      { label: 'Stockout Reduction', value: '67%', description: 'Fewer out-of-stock events' },
      { label: 'Inventory Optimization', value: '45%', description: 'Excess inventory reduction' },
      { label: 'Supplier OTD', value: '96%', description: 'Up from 78% baseline' },
      { label: 'ROI', value: '340%', description: 'First-year return on investment' },
    ],
    testimonial_quote: 'We went from reactive to predictive overnight. The visibility alone was worth the investment.',
    testimonial_author: 'Maria Gonzalez',
    testimonial_role: 'VP of Operations, Atlas Retail Corporation',
    image_url: null,
    published: true,
  },
];

export const demoArticles: Article[] = [
  {
    id: '1',
    created_at: '2025-12-01T00:00:00Z',
    user_id: 'demo-user-id',
    title: 'The Future of AI in Enterprise: Beyond the Hype Cycle',
    slug: 'future-of-ai-enterprise',
    excerpt: 'A pragmatic framework for evaluating AI investments and building sustainable competitive advantages through intelligent automation.',
    content: 'The enterprise AI landscape has matured significantly over the past two years. Organizations that moved beyond proof-of-concept phases are now seeing measurable returns...',
    category: 'AI & Technology',
    image_url: null,
    published: true,
    published_at: '2025-12-01T00:00:00Z',
  },
  {
    id: '2',
    created_at: '2025-11-15T00:00:00Z',
    user_id: 'demo-user-id',
    title: 'Building Resilient Digital Infrastructure for Scale',
    slug: 'resilient-digital-infrastructure',
    excerpt: 'Lessons from modernizing legacy systems across Fortune 500 companies, and why resilience matters more than performance.',
    content: 'In our work with enterprise clients across financial services, healthcare, and manufacturing, one pattern emerges consistently...',
    category: 'Digital Transformation',
    image_url: null,
    published: true,
    published_at: '2025-11-15T00:00:00Z',
  },
  {
    id: '3',
    created_at: '2025-11-01T00:00:00Z',
    user_id: 'demo-user-id',
    title: 'Data-Driven Decision Making: A Framework for Leaders',
    slug: 'data-driven-decisions',
    excerpt: 'How to build a data culture that transforms raw metrics into actionable intelligence without drowning in dashboards.',
    content: 'Every organization claims to be data-driven. Few actually are. The difference lies not in the tools or the data volume...',
    category: 'Strategy',
    image_url: null,
    published: true,
    published_at: '2025-11-01T00:00:00Z',
  },
  {
    id: '4',
    created_at: '2025-10-15T00:00:00Z',
    user_id: 'demo-user-id',
    title: 'Zero Trust Architecture: Implementation Roadmap',
    slug: 'zero-trust-implementation',
    excerpt: 'A practical guide to implementing zero trust security across distributed enterprise environments.',
    content: 'The perimeter is dead. In a world of remote work, cloud services, and interconnected systems, the traditional castle-and-moat approach to security is no longer viable...',
    category: 'Cybersecurity',
    image_url: null,
    published: true,
    published_at: '2025-10-15T00:00:00Z',
  },
];

export const demoCareers: Career[] = [
  {
    id: '1',
    created_at: '2025-12-01T00:00:00Z',
    user_id: 'demo-user-id',
    title: 'Senior Strategy Consultant',
    department: 'Strategy',
    location: 'New York, NY',
    type: 'full-time',
    description: 'Lead strategic engagements with Fortune 500 clients across financial services, technology, and healthcare sectors.',
    requirements: ['MBA or equivalent', '7+ years consulting experience', 'Financial modeling expertise', 'Executive presentation skills'],
    benefits: ['Competitive base + bonus', 'Equity participation', 'Unlimited PTO', 'Annual learning budget'],
    salary_range: '$180K - $250K',
    published: true,
  },
  {
    id: '2',
    created_at: '2025-12-01T00:00:00Z',
    user_id: 'demo-user-id',
    title: 'AI/ML Engineer',
    department: 'Technology',
    location: 'Remote',
    type: 'full-time',
    description: 'Design and implement production ML systems for enterprise clients, from prototype to deployment.',
    requirements: ['MS/PhD in CS, ML, or related field', '5+ years ML engineering', 'Python, PyTorch, cloud platforms', 'Production ML experience'],
    benefits: ['Full remote flexibility', 'Equipment budget', 'Conference sponsorship', 'Research time allocation'],
    salary_range: '$200K - $300K',
    published: true,
  },
  {
    id: '3',
    created_at: '2025-12-01T00:00:00Z',
    user_id: 'demo-user-id',
    title: 'Data Analytics Lead',
    department: 'Analytics',
    location: 'San Francisco, CA',
    type: 'full-time',
    description: 'Drive analytics strategy for major client engagements, building dashboards and predictive models.',
    requirements: ['5+ years data analytics', 'SQL, Python, Tableau/PowerBI', 'Statistical modeling', 'Client-facing experience'],
    benefits: ['Hybrid work model', 'Health & wellness stipend', 'Professional development', '401k matching'],
    salary_range: '$150K - $200K',
    published: true,
  },
];

export const demoTestimonials: Testimonial[] = [
  {
    id: '1',
    created_at: '2025-06-01T00:00:00Z',
    user_id: 'demo-user-id',
    quote: 'Biglabs transformed our approach to digital strategy. Their team combines deep technical expertise with genuine business acumen\u2014a rare combination.',
    author_name: 'Jonathan Park',
    author_role: 'CTO',
    company: 'Meridian Financial Group',
    avatar_url: null,
    published: true,
  },
  {
    id: '2',
    created_at: '2025-08-01T00:00:00Z',
    user_id: 'demo-user-id',
    quote: 'The ROI was visible within the first quarter. They don\'t just deliver reports\u2014they deliver results that move the needle.',
    author_name: 'Dr. Sarah Kimura',
    author_role: 'Chief Medical Officer',
    company: 'Helix Health Systems',
    avatar_url: null,
    published: true,
  },
  {
    id: '3',
    created_at: '2025-10-01T00:00:00Z',
    user_id: 'demo-user-id',
    quote: 'Working with Biglabs felt like adding a world-class technology division to our team. Their precision and execution are unmatched.',
    author_name: 'Maria Gonzalez',
    author_role: 'VP of Operations',
    company: 'Atlas Retail Corporation',
    avatar_url: null,
    published: true,
  },
];

export const demoPricingPlans: PricingPlan[] = [
  {
    id: '1',
    created_at: '2025-01-01T00:00:00Z',
    user_id: 'demo-user-id',
    name: 'Advisory',
    description: 'Strategic guidance for focused initiatives. Ideal for early-stage projects and targeted problem-solving.',
    price: 5000,
    interval: 'monthly',
    features: ['Monthly strategy sessions', 'Market analysis reports', 'Email & Slack support', 'Quarterly business review'],
    highlighted: false,
    sort_order: 1,
  },
  {
    id: '2',
    created_at: '2025-01-01T00:00:00Z',
    user_id: 'demo-user-id',
    name: 'Growth',
    description: 'Full-service consulting for organizations ready to scale. Dedicated team with embedded expertise.',
    price: 15000,
    interval: 'monthly',
    features: ['Weekly strategy sessions', 'Dedicated consultant team', 'Custom analytics dashboards', 'AI-powered reporting', 'Priority support', 'Implementation oversight'],
    highlighted: true,
    sort_order: 2,
  },
  {
    id: '3',
    created_at: '2025-01-01T00:00:00Z',
    user_id: 'demo-user-id',
    name: 'Enterprise',
    description: 'Bespoke engagements for large-scale transformation. White-glove service with C-suite access.',
    price: 0,
    interval: 'project',
    features: ['Dedicated partner lead', 'On-site team deployment', 'Custom AI/ML solutions', '24/7 priority support', 'Board-level reporting', 'Multi-year roadmapping', 'Guaranteed outcomes'],
    highlighted: false,
    sort_order: 3,
  },
];

export const demoConsultations: Consultation[] = [
  {
    id: '1',
    created_at: '2025-12-10T00:00:00Z',
    user_id: 'demo-user-id',
    name: 'David Chen',
    email: 'david@techcorp.io',
    company: 'TechCorp Industries',
    phone: '+1 (555) 123-4567',
    message: 'Interested in AI strategy consulting for our manufacturing operations.',
    preferred_date: '2026-01-15',
    preferred_time: '10:00 AM',
    status: 'confirmed',
  },
  {
    id: '2',
    created_at: '2025-12-12T00:00:00Z',
    user_id: 'demo-user-id',
    name: 'Emily Rodriguez',
    email: 'emily@globalhealth.org',
    company: 'Global Health Initiative',
    phone: null,
    message: 'Looking for help with digital transformation of our patient management systems.',
    preferred_date: '2026-01-20',
    preferred_time: '2:00 PM',
    status: 'pending',
  },
  {
    id: '3',
    created_at: '2025-12-14T00:00:00Z',
    user_id: 'demo-user-id',
    name: 'James Whitfield',
    email: 'j.whitfield@sterling.com',
    company: 'Sterling Ventures',
    phone: '+1 (555) 987-6543',
    message: 'Need cybersecurity assessment for our portfolio companies.',
    preferred_date: null,
    preferred_time: null,
    status: 'pending',
  },
];

export const demoAnalyticsData = {
  overview: {
    totalRevenue: 2450000,
    activeClients: 18,
    projectsCompleted: 47,
    avgSatisfaction: 4.8,
  },
  revenueByMonth: [
    { month: 'Jul', revenue: 180000 },
    { month: 'Aug', revenue: 210000 },
    { month: 'Sep', revenue: 195000 },
    { month: 'Oct', revenue: 240000 },
    { month: 'Nov', revenue: 280000 },
    { month: 'Dec', revenue: 320000 },
  ],
  revenueByService: [
    { service: 'Strategy', revenue: 680000 },
    { service: 'Digital', revenue: 520000 },
    { service: 'AI/ML', revenue: 480000 },
    { service: 'Analytics', revenue: 380000 },
    { service: 'Security', revenue: 240000 },
    { service: 'Operations', revenue: 150000 },
  ],
  clientsByIndustry: [
    { industry: 'Financial Services', count: 6 },
    { industry: 'Healthcare', count: 4 },
    { industry: 'Technology', count: 3 },
    { industry: 'Retail', count: 3 },
    { industry: 'Manufacturing', count: 2 },
  ],
};

export const demoAiInsights = [
  {
    id: '1',
    title: 'Revenue Growth Trend',
    insight: 'Revenue has increased 78% over the past 6 months, driven primarily by Digital Transformation and AI/ML services. Consider expanding the AI team to meet growing demand.',
    type: 'growth',
  },
  {
    id: '2',
    title: 'Client Concentration Risk',
    insight: 'Financial Services represents 33% of revenue. Diversifying into Manufacturing and Energy sectors could reduce concentration risk while opening $2M+ in addressable market.',
    type: 'risk',
  },
  {
    id: '3',
    title: 'Operational Efficiency',
    insight: 'Average project completion time decreased from 4.2 to 3.1 months. The new ML-assisted scoping tool is showing measurable impact on delivery timelines.',
    type: 'efficiency',
  },
];
